### ISSUE TITLE
Make packages available from dev shell

### ISSUE THREAD

**Issue by pnelson** [Yzupnick/example-janet2nix#1]
Works great for the built app in `./result` but it would be even better if I could run the following from `nix develop` shell:

```
janet -e "(import spork/netrepl) (netrepl/server)"
error: could not find module spork/netrepl:
    /nix/store/l52w8dm92k7fm81y6ib5p44n68qiiass-janet-1.32.1/lib/janet/spork/netrepl.jimage
    /nix/store/l52w8dm92k7fm81y6ib5p44n68qiiass-janet-1.32.1/lib/janet/spork/netrepl.janet
    /nix/store/l52w8dm92k7fm81y6ib5p44n68qiiass-janet-1.32.1/lib/janet/spork/netrepl/init.janet
    /nix/store/l52w8dm92k7fm81y6ib5p44n68qiiass-janet-1.32.1/lib/janet/spork/netrepl.so
  in require-1 [boot.janet] on line 3024, column 20
  in import* [boot.janet] on line 3063, column 15
  in _thunk [eval] (tailcall) on line 1, column 1
  in eval-string [boot.janet] on line 2717, column 36
  in e-switch [boot.janet] (tailcall) on line 4051, column 12
  in cli-main [boot.janet] on line 4077, column 13
```

Or even to run changed source from within `nix develop` shell:

```
$ janet main.janet
error: could not find module spork/math:
    /nix/store/l52w8dm92k7fm81y6ib5p44n68qiiass-janet-1.32.1/lib/janet/spork/math.jimage
    /nix/store/l52w8dm92k7fm81y6ib5p44n68qiiass-janet-1.32.1/lib/janet/spork/math.janet
    /nix/store/l52w8dm92k7fm81y6ib5p44n68qiiass-janet-1.32.1/lib/janet/spork/math/init.janet
    /nix/store/l52w8dm92k7fm81y6ib5p44n68qiiass-janet-1.32.1/lib/janet/spork/math.so
  in require-1 [boot.janet] on line 3024, column 20
  in import* [boot.janet] on line 3063, column 15
  in _thunk [main.janet] (tailcall) on line 1, column 1
```

Is this possible?

**Comment by Yzupnick** [comment]
This is possible right now by running something like the “install-deps” command I put in the example flake.

You can probably set it up to run automatically on ‘nix develop’.  I’ll add examples of these to the repo when I get a chance. 

In the future, It would be great if we get the paths to work so that the command is not necessary. I’ll add a ticket to the main repo to that effect.

**Comment by Yzupnick** [comment]
Looking at this a little more, you actually need to run `jpm janet -e "(import spork/netrepl) (netrepl/server)"` or set `JANET_PATH=jpm_tree`.  

This should definitely be done automatically by janet2nix. (Writing up an issue now), but you can set this in the dev shell as well.

**Comment by Yzupnick** [comment]
I released a new version of janet2nix that adds a function `mkJanetTree`. 

The updated example in this repo should now act as you were expecting. I think this is much better than before (with still lots of room to go :wink: ) thanks for the feedback!

Let me know if it works for you.

**Comment by pnelson** [comment]
I finally got around to testing this out and it works great. Thanks!
